# This is a basic workflow to help you get started with Actions

name: publish

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: 27.2
      - uses: tenhaus/get-release-or-tag@v2

      - name: Generate html files from orgmode
        run: |
          emacs index.org --batch -f org-html-export-to-html --kill
          emacs references.org --batch -f org-html-export-to-html --kill
          git rev-parse HEAD > version.html
          ls -lsa
          mkdir html
          mv * html/ || true

      - name: Pushes html files into a branch html
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: html
          FOLDER: html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"



