# This is a basic workflow to help you get started with Actions

name: publish

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@v3.0
      - uses: tenhaus/get-release-or-tag@v2
      - uses: s0/git-publish-subdir-action@develop
      
      - name: build
        run: |
          emacs index.org --batch -f org-html-export-to-html --kill
          emacs references.org --batch -f org-html-export-to-html --kill
          echo ${{ steps.tag.outputs.tag }} version.html
          rm *~ *.org

      - name: push
        env:
          REPO: self
          BRANCH: html
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message



